config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  resources :users, :only => [:new, :create, :show]
  resources :sessions, :only => [:destroy, :new, :create]
  resources :herbs, :only => [:index, :show]
  resources :properties, :only => [:show]
  post '/find_herb' => 'herbs#find_herb'
  resources :preparations, :only => [:show]
  post '/find_preparation' => 'preparations#find_preparation'
  post '/find_property' => 'properties#find_property'

end

app/models/herb.rb
class Herb < ActiveRecord::Base
  belongs_to :part
  has_many :properties, :through => :herbal_properties
  has_many :herbal_properties
  has_many :preparations, :through => :herbal_preparations
  has_many :herbal_preparations

  def specifics
    HerbalProperty.where(:herb_id => self.id, :specific => true)
  end

  def name
    plant = Plant.find(self.plant_id)
    part = Part.find(self.part)
    "#{plant.common_name.capitalize} #{part.structure}"
  end

end

app/models/herbal_preparation.rb
class HerbalPreparation < ActiveRecord::Base
  belongs_to :preparation
  belongs_to :herb
end

app/models/herbal_property.rb
class HerbalProperty < ActiveRecord::Base
  belongs_to :property
  belongs_to :herb
end

app/models/part.rb
class Part < ActiveRecord::Base

end

app/models/plant.rb
class Plant < ActiveRecord::Base
  serialize :species, Array
  serialize :contraindications, Array

  has_many :herbs

end

app/models/preparation.rb
class Preparation <ActiveRecord::Base

  has_many :herbs, through: :herbal_preparations
  has_many :herbal_preparations
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :herbs, through: :herbal_properties
  has_many :herbal_properties
end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :username, :email
  has_secure_password
  validates_presence_of :password_confirmation, on: :create

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def current_user
    User.find(session[:current_user_id]) if session[:current_user_id]
  end

  helper_method :current_user

end

app/controllers/herbs_controller.rb
class HerbsController <ApplicationController

  def index

  end

  def find_herb
    if params[:plant][:common_name] != ''
      redirect_to herb_path(params[:plant][:common_name])
    else
      redirect_to herbs_path
    end
  end

  def show
    @plant = Plant.find(params[:id])
  end

end

app/controllers/preparations_controller.rb
class PreparationsController < ApplicationController

  def show
    @preparation = Preparation.find(params[:id])
  end

  def find_preparation
    if params[:preparation][:name] != ''
      redirect_to preparation_path(params[:preparation][:name])
    else
      redirect_to herbs_path
    end
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def show
    @property = Property.find(params[:id])
  end

  def find_property
    if params[:property][:name] != ''
      redirect_to property_path(params[:property][:name])
    else
      redirect_to herbs_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    session.clear
    flash[:notice] = 'You have successfully logged out'
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:current_user_id] = @user.id
      flash[:notice] = 'Your login was successful!'
      redirect_to user_path(current_user)
    else
      @user = User.new
      flash.now[:error] = 'Email and/or Password is incorrect.'
      render :new
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(allowed_parameters)
    if @user.save
      session[:current_user_id] = @user.id
      flash[:notice] = 'Your registration was successful!'
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def show

  end

  private

  def allowed_parameters
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/herbs/index.html.erb
<%= form_for :plant, url: find_herb_path do |f| %>
  <%= f.collection_select(:common_name, Plant.all, :id, :common_name, {:prompt => true}) %>
  <%= f.submit 'Tell me about this herb' %>
<% end %>
<%= form_for :preparation, url: find_preparation_path do |f| %>
  <%= f.collection_select(:name, Preparation.all, :id, :name, {:prompt => true}) %>
  <%= f.submit 'Tell me about this preparation' %>
<% end %>
<%= form_for :property, url: find_property_path do |f| %>
  <%= f.collection_select(:name, Property.all, :id, :name, {:prompt => true}) %>
  <%= f.submit 'Tell me about this property' %>
<% end %>

app/views/herbs/show.html.erb
<h1>Plant Name: <%= @plant.common_name.capitalize %></h1>
<div class="plant-box">
  <div class="illustration">
    <%= image_tag @plant.image %>
  </div>
  <div class="plant-data">
    <div class="species">
      <h2>Species</h2>
      <% @plant.species.each do |binomial| %>
        <h3><i><%= binomial %></i></h3>
      <% end %>
    </div>
    <div class="contraindications">
      <h2>Contraindications</h2>
      <% if @plant.contraindications.any? %>
        <% @plant.contraindications.each do |contraindication| %>
          <h3><%= contraindication %></h3>
        <% end %>
      <% else %>
        <h3>No major known contraindications, but always ask your body!</h3>
      <% end %>
    </div>
    <div class="parts">
      <h2>Part(s) used:</h2>
      <% @plant.herbs.each do |herb| %>
        <h3><%= herb.part.structure %></h3>

        <div class="specific">
          <h4>Specific Use</h4>
          <% herb.specifics.each do |specific| %>
            <h5><%= specific.property.name %></h5>
          <% end %>
        </div>
        <div class="properties">
          <h4>Actions</h4>
          <% herb.properties.each do |property| %>
            <h5><%= link_to property.name, property_path(property) %></h5>
          <% end %>
        </div>
        <div class="preparations">
          <h4>Preparations</h4>
          <% herb.preparations.each do |preparation| %>
            <h5><%= link_to preparation.name, preparation_path(preparation) %></h5>
          <% end %>
        </div>
        <div class="best_time_to_collect">
          <h4>Best Time to Collect</h4>
          <h5><%= herb.time_to_collect %></h5>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HerbalNotebook</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'Vervain.png' %>
</head>
<body>
<nav>
  <% if current_user %>
    <div class="logo">
      <%= link_to 'Herbal Notebook', user_path(current_user) %>
    </div>
    <div class="session_nav">
      <%= link_to 'Logout', session_path(current_user), method: :delete %>
    </div>
  <% else %>
    <div class="logo">
      <%= link_to 'Herbal Notebook', root_path %>
    </div>
    <div class="session_nav">
      <%= link_to 'Register', new_user_path %>
      <%= link_to 'Login', new_session_path %>
    </div>
  <% end %>
</nav>
<div class="nav_underscore"></div>

<% if flash.any? %>
<div>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
<% end %>
</div>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/preparations/show.html.erb
<h1>Herbal Property: <%= @preparation.name.capitalize %></h1>
<div class="preparation">
  <h2><%= @preparation.recipe %></h2>
</div>
<div class="herbs">
  <h2>Herbs that are great with this preparation:</h2>
  <ul>
    <% @preparation.herbs.each do |herb| %>
      <li><%= link_to herb.name, herb_path(herb.plant_id) %></li>
    <% end %>
  </ul>
</div>

app/views/properties/show.html.erb
<h1>Herbal Property: <%= @property.name.capitalize %></h1>
<div class="property">
  <h2><%= @property.definition.capitalize %>.</h2>
</div>
<div class="herbs">
  <h2>Herbs with this property:</h2>
  <ul>
  <% @property.herbs.each do |herb| %>
    <li><%= link_to herb.name, herb_path(herb.plant_id) %></li>
  <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<div class="signin-form">
  <% if @user.errors.any? %>
    <div class="error">
      <% @user.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>
  <%= form_for @user do |f| %>
    <div>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div>
      <%= f.submit "Register" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Welcome, <%= current_user.username %>!</h1>

app/views/welcome/index.html.erb
<h1>Welcome to the Herbal Notebook, kind stranger!</h1>

<h3>This is a work in very early progress. The current data is from my personal material medica but is not complete. I am currently working on the underlying architecture and am looking forward to a more complete dictionary.</h3>

<h2><%= link_to 'Care to browse our little herbal dictionary?', herbs_path %></h2>